# Generated by Django 2.1.7 on 2019-03-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190331_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embedded',
            field=models.TextField(blank=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/arquivo'),
        ),
    ]
