# Generated by Django 2.1.7 on 2019-03-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190331_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='embedded',
            field=models.CharField(blank=True, max_length=250, verbose_name='Link de vídeo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='arquivo', verbose_name='Arquivo'),
        ),
    ]
