# Generated by Django 2.1.7 on 2019-04-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descricao_og',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='img_og',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_og',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='origem_og',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo_og',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='-', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='embedded',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Cole aqui o Link para videos (Youtube & Vimeo)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Cole aqui o Link para outras paginas'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='-', max_length=100, verbose_name='Título'),
        ),
    ]
