# Generated by Django 2.1.7 on 2019-04-11 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190410_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField(blank=True, max_length=250, null=True, verbose_name='Cole aqui o Link para outras paginas')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='blog_images')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='-', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='post sem título', max_length=100, verbose_name='Título  (o titulo do seu post servirá como link para editá-lo posteriormente)'),
        ),
    ]
