# Generated by Django 2.1.7 on 2019-04-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190411_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisos',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='avisos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='avisos_images'),
        ),
    ]
