# Generated by Django 2.1.7 on 2019-04-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190411_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisos',
            options={'verbose_name_plural': 'Avisos'},
        ),
        migrations.RemoveField(
            model_name='avisos',
            name='autor',
        ),
        migrations.AlterField(
            model_name='post',
            name='embedded',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Cole aqui o Link de videos (Youtube & Vimeo)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Cole aqui o Link de outras paginas'),
        ),
    ]
