# Generated by Django 2.1.7 on 2019-04-12 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_avisos_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
